export type Thinking =
  "auto" | "instant" | "low" | "medium" | "high" | "max" | "off";

export interface CatalogModel {
  id: string;
  label: string;
  group: "auto" | "v28" | "v27" | "apex" | "fast" | "other";
  thinking?: Thinking[];
  context: number;
  maxOut: number;
  agent: boolean;
  tags?: string[];
}

export const CATALOG: CatalogModel[] = [
  // Auto Router
  {
    id: "bailu-auto",
    label: "Auto (Smart Router)",
    group: "auto",
    context: 256000,
    maxOut: 128000,
    agent: true,
    tags: ["Router", "256K"],
  },

  // Bailu 2.8 Generation (Flagship Opus 5 Benchmark)
  {
    id: "bailu-2.8",
    label: "BaiLu 2.8 Flagship (1M)",
    group: "v28",
    thinking: ["instant", "low", "medium", "high", "max"],
    context: 1048576,
    maxOut: 131072,
    agent: true,
    tags: ["1M", "Flagship", "Vision"],
  },
  {
    id: "bailu-2.8-nvfp8",
    label: "BaiLu 2.8 NVFP8 (1M)",
    group: "v28",
    thinking: ["low", "medium", "high"],
    context: 1048576,
    maxOut: 128000,
    agent: true,
    tags: ["1M", "NVFP8"],
  },
  {
    id: "bailu-2.8-lite",
    label: "BaiLu 2.8 Lite (MoE)",
    group: "v28",
    thinking: ["low", "medium", "high", "max"],
    context: 262144,
    maxOut: 65536,
    agent: true,
    tags: ["262K", "MoE"],
  },
  {
    id: "bailu-2.8-free",
    label: "BaiLu 2.8 Free",
    group: "v28",
    thinking: ["instant", "low", "medium", "high", "max"],
    context: 262144,
    maxOut: 218000,
    agent: true,
    tags: ["262K", "Free"],
  },
  {
    id: "bailu-2.8-preview",
    label: "BaiLu 2.8 Preview (1M)",
    group: "v28",
    context: 1048572,
    maxOut: 131072,
    agent: true,
    tags: ["1M", "Preview"],
  },
  {
    id: "bailu-2.8-vl-2B",
    label: "BaiLu 2.8 VL 2B (Agent)",
    group: "v28",
    context: 256000,
    maxOut: 65536,
    agent: true,
    tags: ["256K", "Edge-Agent"],
  },

  // Bailu 2.7 Generation (Opus 4.6 Benchmark)
  {
    id: "bailu-2.7",
    label: "BaiLu 2.7 Flagship",
    group: "v27",
    context: 262140,
    maxOut: 128000,
    agent: true,
    tags: ["262K", "Flagship"],
  },
  {
    id: "bailu-2.7-1m",
    label: "BaiLu 2.7 1M Context",
    group: "v27",
    context: 1024570,
    maxOut: 128000,
    agent: true,
    tags: ["1M", "Long-Context"],
  },
  {
    id: "bailu-2.7-free",
    label: "BaiLu 2.7 Free (NVFP4)",
    group: "v27",
    context: 262144,
    maxOut: 262144,
    agent: true,
    tags: ["262K", "Free"],
  },
  {
    id: "bailu-2.7-fast",
    label: "BaiLu 2.7 Fast",
    group: "v27",
    context: 256000,
    maxOut: 128000,
    agent: true,
    tags: ["256K", "Fast"],
  },
  {
    id: "bailu-2.7-lite",
    label: "BaiLu 2.7 Lite",
    group: "v27",
    thinking: ["instant"],
    context: 131072,
    maxOut: 50000,
    agent: true,
    tags: ["131K", "Diffusion"],
  },
  {
    id: "bailu-2.7-lite-vl",
    label: "BaiLu 2.7 Lite VL",
    group: "v27",
    context: 262144,
    maxOut: 128000,
    agent: true,
    tags: ["262K", "Vision"],
  },
  {
    id: "bailu-2.7-vl-350m",
    label: "BaiLu 2.7 VL 350M",
    group: "v27",
    context: 32768,
    maxOut: 32000,
    agent: true,
    tags: ["32K", "Edge-Vision"],
  },

  // Apex Line (Dense, Agentic & Code Specialist)
  {
    id: "bailu-apex-2.7",
    label: "Apex 2.7 (512K)",
    group: "apex",
    thinking: ["instant", "medium", "max"],
    context: 512000,
    maxOut: 512000,
    agent: true,
    tags: ["512K", "Multimodal"],
  },
  {
    id: "bailu-apex",
    label: "Apex (Alias 2.7)",
    group: "apex",
    thinking: ["instant", "medium", "max"],
    context: 512000,
    maxOut: 512000,
    agent: true,
    tags: ["512K", "Multimodal"],
  },
  {
    id: "bailu-apex-openclaw",
    label: "Apex OpenClaw (Agent)",
    group: "apex",
    thinking: ["low", "medium", "high"],
    context: 256000,
    maxOut: 128000,
    agent: true,
    tags: ["256K", "Tool-Calling"],
  },
  {
    id: "bailu-apex-2",
    label: "Apex 2 (1M Dense)",
    group: "apex",
    context: 1048000,
    maxOut: 256000,
    agent: true,
    tags: ["1M", "Dense-Coding"],
  },
  {
    id: "bailu-apex-2.6",
    label: "Apex 2.6 Free (512K)",
    group: "apex",
    context: 512000,
    maxOut: 256000,
    agent: true,
    tags: ["512K", "Free-Multimodal"],
  },
  {
    id: "bailu-apex-172b",
    label: "Apex 172B Coding",
    group: "apex",
    context: 200000,
    maxOut: 196000,
    agent: true,
    tags: ["200K", "Architecture"],
  },
  {
    id: "bailu-apex-120b",
    label: "Apex 120B Long-Attn",
    group: "apex",
    context: 252000,
    maxOut: 128000,
    agent: true,
    tags: ["252K", "Long-Repo"],
  },
  {
    id: "bailu-apex-30B",
    label: "Apex 30B SynFlow Free",
    group: "apex",
    context: 256000,
    maxOut: 128000,
    agent: true,
    tags: ["256K", "SynFlow"],
  },
  {
    id: "bailu-apex-25b",
    label: "Apex 25B Dense",
    group: "apex",
    context: 200000,
    maxOut: 62400,
    agent: true,
    tags: ["200K", "Dense"],
  },
  {
    id: "bailu-apex-2.5",
    label: "Apex 2.5 Multimodal",
    group: "apex",
    context: 131072,
    maxOut: 131072,
    agent: true,
    tags: ["131K", "Vision"],
  },
  {
    id: "bailu-apex-2.5-lite",
    label: "Apex 2.5 Lite (512K)",
    group: "apex",
    context: 524288,
    maxOut: 65500,
    agent: true,
    tags: ["512K", "Vision"],
  },
  {
    id: "bailu-apex-2.1-lite",
    label: "Apex 2.1 Lite (1M)",
    group: "apex",
    context: 1000000,
    maxOut: 65500,
    agent: true,
    tags: ["1M", "Fast-Agent"],
  },
  {
    id: "bailu-apex-1b",
    label: "Apex 1B CoT",
    group: "apex",
    context: 32768,
    maxOut: 32000,
    agent: true,
    tags: ["32K", "Micro-CoT"],
  },

  // Fast / Edge Line
  {
    id: "bailu-dash-free",
    label: "Dash Free (High-Concurrency)",
    group: "fast",
    context: 256000,
    maxOut: 64000,
    agent: true,
    tags: ["256K", "Free"],
  },
  {
    id: "bailu-dash",
    label: "Dash Fast",
    group: "fast",
    context: 262144,
    maxOut: 32768,
    agent: true,
    tags: ["262K", "Fast"],
  },
  {
    id: "bailu-edge-2",
    label: "Edge 2 Free",
    group: "fast",
    context: 262144,
    maxOut: 262144,
    agent: true,
    tags: ["262K", "Free"],
  },
  {
    id: "bailu-edge-8b",
    label: "Edge 8B Agent MoE",
    group: "fast",
    context: 256000,
    maxOut: 65536,
    agent: true,
    tags: ["256K", "Agent-MoE"],
  },
  {
    id: "bailu-edge-0.5b",
    label: "Edge 0.5B Ultra-Light",
    group: "fast",
    context: 262144,
    maxOut: 64000,
    agent: true,
    tags: ["262K", "Free"],
  },
  {
    id: "bailu-edge-thinking",
    label: "Edge Thinking CoT",
    group: "fast",
    context: 200000,
    maxOut: 124000,
    agent: true,
    tags: ["200K", "CoT"],
  },

  // Other / Frontier & Previous Gen
  {
    id: "Yuyu-Titan-3.0",
    label: "Yuyu Titan 3.0 Coding",
    group: "other",
    context: 200000,
    maxOut: 80000,
    agent: true,
    tags: ["200K", "Code-Frontier"],
  },
  {
    id: "Yuyu-Legend-Preview",
    label: "Yuyu Legend Titan Preview",
    group: "other",
    context: 524288,
    maxOut: 128000,
    agent: true,
    tags: ["524K", "Preview"],
  },
  {
    id: "yuyu-air",
    label: "Yuyu Air MoE Free",
    group: "other",
    context: 262144,
    maxOut: 131000,
    agent: true,
    tags: ["262K", "MoE-Free"],
  },
  {
    id: "bailu-2.6",
    label: "BaiLu 2.6 General",
    group: "other",
    context: 256000,
    maxOut: 64000,
    agent: true,
    tags: ["256K", "General"],
  },
  {
    id: "bailu-2.6-thinking",
    label: "BaiLu 2.6 Thinking CoT",
    group: "other",
    context: 200000,
    maxOut: 124000,
    agent: true,
    tags: ["200K", "CoT"],
  },
  {
    id: "bailu-2.6-preview",
    label: "BaiLu 2.6 Preview",
    group: "other",
    context: 256000,
    maxOut: 128000,
    agent: true,
    tags: ["256K", "Preview"],
  },
  {
    id: "bailu-im-30b-test",
    label: "BaiLu IM 30B Test",
    group: "other",
    thinking: ["off", "low", "medium", "high"],
    context: 262140,
    maxOut: 256000,
    agent: true,
    tags: ["262K", "Industrial"],
  },
];

export const SYSTEM_PROMPTS: Record<string, string> = {
  code: "You are Bailu Agent in Code mode powered by Antigravity engineering methodology. Implement and edit code with clean patterns, strict typing, and defensive security. Keep code concise, verified, and free of hallucinations.",
  plan: "You are Bailu Agent in Plan mode powered by Antigravity spec-driven methodology. Produce structured, bite-sized implementation plans with clear acceptance criteria and risk assessment. Do not write full code unless asked.",
  ask: "You are Bailu Agent in Ask mode powered by Antigravity engineering expertise. Answer questions about code and architecture concisely. Cite sources and evidence.",
  debug:
    "You are Bailu Agent in Debug mode powered by Antigravity systematic debugging. Execute 4 phases: Investigate root cause, Analyze execution flow, Hypothesize minimal fix, Verify against regression.",
  review:
    "You are Bailu Agent in Review mode powered by Antigravity 5-dimension code review: evaluate correctness, readability, architecture, security, and performance. Prioritize findings by severity.",
  arch: "You are Bailu Agent in Architect mode powered by Antigravity architecture patterns. Design systems using Clean Architecture, Hexagonal Architecture, and Domain-Driven Design. Produce C4 diagrams, ADRs, and component boundaries. Focus on scalability, maintainability, and separation of concerns.",
};

export const SYSTEM_PROMPTS_ID: Record<string, string> = {
  code: "Anda adalah Bailu Agent mode Code berbasis metodologi engineering Antigravity. Implementasikan dan sunting kode dengan pola bersih, tipe presisi, dan keamanan defensif. Jaga kode tetap ringkas, terverifikasi, dan bebas halusinasi.",
  plan: "Anda adalah Bailu Agent mode Plan berbasis metodologi spec-driven Antigravity. Buat rencana implementasi terstruktur dengan kriteria penerimaan dan mitigasi risiko.",
  ask: "Anda adalah Bailu Agent mode Ask berbasis keahlian arsitektur Antigravity. Jawab pertanyaan seputar kode secara ringkas dan berbasis bukti.",
  debug:
    "Anda adalah Bailu Agent mode Debug berbasis debugging sistematik Antigravity. Jalankan 4 fase: Investigasi akar masalah, Analisis alur, Hipotesis perbaikan minimal, dan Verifikasi bukti.",
  review:
    "Anda adalah Bailu Agent mode Review berbasis 5 dimensi Antigravity: tinjau kebenaran, keterbacaan, arsitektur, keamanan, dan performa. Urutkan temuan berdasarkan keparahan.",
  arch: "Anda adalah Bailu Agent mode Architect berbasis pola arsitektur Antigravity. Rancang sistem menggunakan Clean Architecture, Hexagonal Architecture, dan Domain-Driven Design. Hasilkan diagram C4, ADR, dan batas komponen. Fokus pada skalabilitas, kemudahan pemeliharaan, dan pemisahan tanggung jawab.",
};

export function promptFor(mode: string, locale: string): string {
  const table = locale === "id" ? SYSTEM_PROMPTS_ID : SYSTEM_PROMPTS;
  return table[mode] || table.code;
}
