// @ts-nocheck
/* eslint-disable @typescript-eslint/no-explicit-any, no-useless-escape */
// biome-ignore-all lint/correctness/noUnusedVariables: nonce param forwarded via HTML template
// biome-ignore-all lint/style/useTemplate: intentional regex strings in browser JS
/**
 * Bailu Agent WebView v1.1.9
 * Modern, Elegant, and Accessible Sidebar Interface for Code-OSS & VS Code Ecosystem
 */

/** Inline JavaScript source for the webview.
 *  Kept as a plain function string to avoid backtick / regex escaping issues
 *  when embedded inside a template literal in getWebviewHtml().
 */
function getWebviewScript(_nonce?: string): string {
  // We return the entire script body as a string — no template literals allowed inside.
  // nonce is injected into the <script nonce="..."> attribute by getWebviewHtml
  const scriptLines: string[] = [
    "const vscode = acquireVsCodeApi();",
    "const $ = function(id){ return document.getElementById(id); };",
    "let catalog = [];",
    "let bookmarks = [];",
    "let busy = false;",
    "let welcomed = false;",
    "let hydrating = false;",
    "let locale = 'en';",
    "let theme = 'auto';",
    "let activeStreamEl = null;",
    "",
    "function applyTheme(v) {",
    "  theme = (v === 'dark' || v === 'light') ? v : 'auto';",
    "  document.body.classList.remove('theme-dark', 'theme-light');",
    "  if (theme === 'dark') document.body.classList.add('theme-dark');",
    "  if (theme === 'light') document.body.classList.add('theme-light');",
    "}",
    "",
    "var I18N = {",
    "  en: {",
    "    newTask: 'New task', settings: 'Settings', back: 'Back',",
    "    placeholder: 'Task… (Enter send, Shift+Enter newline) — @skill:name to inject a skill',",
    "    send: 'Send', stop: 'Stop', ready: 'Ready',",
    "    welcome: 'Set the API token in Settings. Default model: bailu-auto. Tip: Use @skill:<name> in your message to inject a skill runbook.',",
    "    taskNew: 'New task started.',",
    "    hint: 'The token is stored in VS Code SecretStorage, not in settings.json.',",
    "    save: 'Save & test connection', tokenPh: 'sk… or Bailu token',",
    "    tokenSaved: 'Token saved — enter a new one to replace',",
    "    settingsTitle: 'Settings', defModel: 'Default model', defThink: 'Default thinking', lang: 'Language',",
    "    tinyfishTitle: 'TinyFish API Key (Search & Crawler)',",
    "    export: 'Export transcript', snap: 'Save snapshot', copy: 'Copy',",
    "    welcomeTitle: 'What would you like to build?',",
    "    welcomeDesc: 'Agentic coding assistant powered by BAILU AI & Antigravity engineering methodology.',",
    "    qExplain: 'Explain active file',",
    "    qRefactor: 'Refactor & clean code',",
    "    qTests: 'Generate unit tests',",
    "    qDebug: 'Debug & find defects'",
    "  },",
    "  id: {",
    "    newTask: 'Task baru', settings: 'Pengaturan', back: 'Kembali',",
    "    placeholder: 'Tugas… (Enter kirim, Shift+Enter baris baru) — @skill:nama untuk inject skill',",
    "    send: 'Kirim', stop: 'Stop', ready: 'Siap',",
    "    welcome: 'Atur API token di Pengaturan. Model default: bailu-auto. Tips: Gunakan @skill:<nama> untuk inject skill.',",
    "    taskNew: 'Task baru.',",
    "    hint: 'Token disimpan di SecretStorage VS Code, tidak ditulis ke settings.json.',",
    "    save: 'Simpan & tes koneksi', tokenPh: 'sk… atau token Bailu',",
    "    tokenSaved: 'Token tersimpan — isi untuk ganti',",
    "    settingsTitle: 'Pengaturan', defModel: 'Model default', defThink: 'Thinking default', lang: 'Bahasa',",
    "    tinyfishTitle: 'API Key TinyFish (Pencarian & Crawler)',",
    "    export: 'Ekspor transkrip', snap: 'Simpan snapshot', copy: 'Salin',",
    "    welcomeTitle: 'Apa yang ingin Anda bangun hari ini?',",
    "    welcomeDesc: 'Asisten coding agentic bertenaga BAILU AI & metodologi engineering Antigravity.',",
    "    qExplain: 'Jelaskan file aktif',",
    "    qRefactor: 'Refaktor & rapikan kode',",
    "    qTests: 'Buat unit test otomatis',",
    "    qDebug: 'Debug & cari error'",
    "  }",
    "};",
    "function t(key) { return (I18N[locale] || I18N.en)[key] || I18N.en[key]; }",
    "",
    "function applyLocale() {",
    "  var L = I18N[locale] || I18N.en;",
    "  var inp = $('input'); if (inp) inp.placeholder = L.placeholder;",
    "  var ak = $('apiKey');",
    "  if (ak) ak.placeholder = (ak.dataset.saved === '1' || ak.placeholder.indexOf('Token') >= 0 || ak.placeholder.indexOf('tersimpan') >= 0) ? L.tokenSaved : L.tokenPh;",
    "  var bn = $('btnNew'); if (bn) { bn.title = L.newTask; bn.setAttribute('aria-label', L.newTask); }",
    "  var bs = $('btnSet'); if (bs) { bs.title = L.settings; bs.setAttribute('aria-label', L.settings); }",
    "  var bb = $('btnBack'); if (bb) bb.setAttribute('aria-label', L.back);",
    "  var bsn = $('btnSend'); if (bsn) { var spn = bsn.querySelector('span'); if (spn) spn.textContent = L.send; else bsn.textContent = L.send; }",
    "  var bst = $('btnStop'); if (bst) { var sps = bst.querySelector('span'); if (sps) sps.textContent = '■ ' + L.stop; else bst.textContent = '■ ' + L.stop; }",
    "  var bsv = $('btnSave'); if (bsv) bsv.textContent = L.save;",
    "  var be = $('btnExport'); if (be) { be.title = L.export; be.setAttribute('aria-label', L.export); }",
    "  var bsn2 = $('btnSnap'); if (bsn2) { bsn2.title = L.snap; bsn2.setAttribute('aria-label', L.snap); }",
    "  var hs = $('hintSecret'); if (hs) hs.textContent = L.hint;",
    "  var st = $('lblSettingsTitle'); if (st) st.textContent = L.settingsTitle;",
    "  var dm = $('lblDefModel'); if (dm) dm.textContent = L.defModel;",
    "  var dt = $('lblDefThink'); if (dt) dt.textContent = L.defThink;",
    "  var ll = $('lblLocale'); if (ll) ll.textContent = L.lang;",
    "  var tf = $('lblTinyfish'); if (tf) tf.textContent = L.tinyfishTitle;",
    "  var wt = $('welcomeTitle'); if (wt) wt.textContent = L.welcomeTitle;",
    "  var wd = $('welcomeDesc'); if (wd) wd.textContent = L.welcomeDesc;",
    "  var qe = $('qExplainText'); if (qe) qe.textContent = L.qExplain;",
    "  var qr = $('qRefactorText'); if (qr) qr.textContent = L.qRefactor;",
    "  var qt = $('qTestsText'); if (qt) qt.textContent = L.qTests;",
    "  var qd = $('qDebugText'); if (qd) qd.textContent = L.qDebug;",
    "}",
    "",
    "/* Lightweight Markdown renderer — no external dependencies */",
    "function escHtml(s) {",
    "  return String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');",
    "}",
    "function inlineMd(s) {",
    "  s = s.replace(/`([^`]+)`/g, function(_,c){ return '<code>' + escHtml(c) + '</code>'; });",
    String.raw`  s = s.replace(/\*\*\*(.+?)\*\*\*/g, function(_,c){ return '<strong><em>' + c + '</em></strong>'; });`,
    String.raw`  s = s.replace(/\*\*(.+?)\*\*/g, function(_,c){ return '<strong>' + c + '</strong>'; });`,
    "  s = s.replace(/__(.+?)__/g, function(_,c){ return '<strong>' + c + '</strong>'; });",
    String.raw`  s = s.replace(/\*(.+?)\*/g, function(_,c){ return '<em>' + c + '</em>'; });`,
    "  s = s.replace(/_([^_]+)_/g, function(_,c){ return '<em>' + c + '</em>'; });",
    "  s = s.replace(/~~(.+?)~~/g, function(_,c){ return '<del>' + c + '</del>'; });",
    String.raw`  s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g, function(_,txt,url){ return '<a href="' + url + '" target="_blank" rel="noopener">' + txt + '</a>'; });`,
    "  return s;",
    "}",
    "function renderMd(text) {",
    String.raw`  var lines = text.split('\n');`,
    "  var html = '';",
    "  var inCode = false;",
    "  var codeLines = [];",
    "  var codeLang = '';",
    "  var inTable = false;",
    "  var tableRows = [];",
    "  function flushTable() {",
    "    if (!tableRows.length) return;",
    "    var th = '<table><thead><tr>';",
    "    var rawH = tableRows[0].split('|');",
    "    if (rawH.length > 1 && !rawH[0].trim()) rawH.shift();",
    "    if (rawH.length > 0 && !rawH[rawH.length - 1].trim()) rawH.pop();",
    "    rawH.forEach(function(h){ th += '<th>' + inlineMd(escHtml(h.trim())) + '</th>'; });",
    "    th += '</tr></thead><tbody>';",
    "    for (var i = 2; i < tableRows.length; i++) {",
    "      var rawC = tableRows[i].split('|');",
    "      if (rawC.length > 1 && !rawC[0].trim()) rawC.shift();",
    "      if (rawC.length > 0 && !rawC[rawC.length - 1].trim()) rawC.pop();",
    "      th += '<tr>';",
    "      rawC.forEach(function(c){ th += '<td>' + inlineMd(escHtml(c.trim())) + '</td>'; });",
    "      th += '</tr>';",
    "    }",
    "    th += '</tbody></table>';",
    "    html += th;",
    "    tableRows = []; inTable = false;",
    "  }",
    "  for (var li = 0; li < lines.length; li++) {",
    "    var line = lines[li];",
    "    if (line.startsWith('```')) {",
    String.raw`      if (inCode) { html += '<div class="code-box"><div class="code-head"><span class="code-lang">' + escHtml(codeLang || 'code') + '</span><button type="button" class="code-copy" aria-label="Copy code"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg> <span>' + t('copy') + '</span></button></div><pre><code>' + escHtml(codeLines.join('\n')) + '</code></pre></div>'; inCode = false; codeLines = []; codeLang = ''; }`,
    "      else { if (inTable) flushTable(); inCode = true; codeLang = line.slice(3).trim(); }",
    "      continue;",
    "    }",
    "    if (inCode) { codeLines.push(line); continue; }",
    String.raw`    if (/^\|.+\|/.test(line)) { inTable = true; tableRows.push(line); continue; }`,
    "    if (inTable) flushTable();",
    "    if (!line.trim()) { html += '<p></p>'; continue; }",
    "    var hm = /^(#{1,4}) (.+)/.exec(line);",
    "    if (hm) { html += '<h' + hm[1].length + '>' + inlineMd(escHtml(hm[2])) + '</h' + hm[1].length + '>'; continue; }",
    "    if (/^[-*+] /.test(line)) { html += '<ul><li>' + inlineMd(escHtml(line.slice(2))) + '</li></ul>'; continue; }",
    String.raw`    if (/^\d+\. /.test(line)) { html += '<ol><li>' + inlineMd(escHtml(line.replace(/^\d+\. /, ''))) + '</li></ol>'; continue; }`,
    "    if (/^> ?/.test(line)) { html += '<blockquote>' + inlineMd(escHtml(line.replace(/^> ?/, ''))) + '</blockquote>'; continue; }",
    "    if (/^---+$/.test(line.trim())) { html += '<hr/>'; continue; }",
    "    html += '<p>' + inlineMd(escHtml(line)) + '</p>';",
    "  }",
    String.raw`  if (inCode) html += '<div class="code-box"><div class="code-head"><span class="code-lang">' + escHtml(codeLang || 'code') + '</span><button type="button" class="code-copy" aria-label="Copy code"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg> <span>' + t('copy') + '</span></button></div><pre><code>' + escHtml(codeLines.join('\n')) + '</code></pre></div>';`,
    "  if (inTable) flushTable();",
    String.raw`  html = html.replace(/<\/ul>(\s*)<ul>/g, '').replace(/<\/ol>(\s*)<ol>/g, '');`,
    "  return html;",
    "}",
    "",
    "function show(id) {",
    "  document.querySelectorAll('.screen').forEach(function(s){ s.classList.remove('on'); });",
    "  $(id).classList.add('on');",
    "  if (id === 'settings') { var ak = $('apiKey'); if (ak) ak.focus(); }",
    "  else { var inp = $('input'); if (inp) inp.focus(); }",
    "}",
    "function addMsg(role, text) {",
    "  var wc = $('welcomeCard');",
    "  if (wc && role !== 'sys') wc.style.display = 'none';",
    "  var wrap = document.createElement('div');",
    "  wrap.className = 'msg-wrap ' + role;",
    "  var el = document.createElement('div');",
    "  el.className = 'msg ' + role;",
    "  var r = document.createElement('div');",
    "  r.className = 'role';",
    "  var rl = document.createElement('span');",
    "  rl.className = 'role-badge';",
    "  var roleLabel = role;",
    "  if (role === 'user') {",
    "    roleLabel = '👤 ' + (locale === 'id' ? 'Anda' : 'You');",
    "  } else if (role === 'assistant') {",
    "    var curMdl = ($('model') || {}).value || 'Bailu';",
    "    roleLabel = '🤖 ' + curMdl;",
    "  } else if (role === 'sys') {",
    "    roleLabel = '⚙ ' + (locale === 'id' ? 'Sistem' : 'System');",
    "  }",
    "  rl.textContent = roleLabel;",
    "  r.appendChild(rl);",
    "  if (role === 'assistant') {",
    "    var cpBtn = document.createElement('button');",
    "    cpBtn.type = 'button';",
    "    cpBtn.className = 'copy-btn';",
    '    var copySvg = \'<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>\';',
    "    cpBtn.innerHTML = copySvg + ' <span>' + t('copy') + '</span>';",
    "    cpBtn.title = t('copy');",
    "    cpBtn.setAttribute('aria-label', t('copy'));",
    "    cpBtn.onclick = function() {",
    "      var bodyEl = el.querySelector('.body');",
    "      var txt = bodyEl ? (bodyEl.dataset.raw || bodyEl.textContent || '') : '';",
    "      if (navigator.clipboard) {",
    "        navigator.clipboard.writeText(txt).then(function(){",
    "          cpBtn.innerHTML = '✓ ' + (locale === 'id' ? 'Tersalin' : 'Copied');",
    "          setTimeout(function(){",
    "            cpBtn.innerHTML = copySvg + ' <span>' + t('copy') + '</span>';",
    "          }, 1500);",
    "        });",
    "      }",
    "    };",
    "    r.appendChild(cpBtn);",
    "  }",
    "  var b = document.createElement('div');",
    "  b.className = 'body' + (role === 'assistant' ? ' md' : '');",
    "  if (role === 'assistant') {",
    "    b.dataset.raw = text || '';",
    "    b.innerHTML = renderMd(text || '');",
    "  } else {",
    "    b.textContent = text;",
    "  }",
    "  el.appendChild(r);",
    "  el.appendChild(b);",
    "  wrap.appendChild(el);",
    "  var msgs = $('msgs'); if (msgs) { msgs.appendChild(wrap); msgs.scrollTop = msgs.scrollHeight; }",
    "  return b;",
    "}",
    "function fillModels(sel, list) {",
    "  if (!sel) return;",
    "  hydrating = true;",
    "  sel.innerHTML = '';",
    "  var groups = { bookmarks: 'Bookmarks', auto: 'Auto', v28: '2.8 Flagship', v27: '2.7 Line', apex: 'Apex & Frontier', fast: 'Dash & Edge', other: 'Other' };",
    "  var used = {};",
    "  var marked = (bookmarks || []).map(String);",
    "  var pinned = list.filter(function(m){ return marked.indexOf(m.id) >= 0; });",
    "  if (pinned.length) {",
    "    var g = document.createElement('optgroup');",
    "    g.label = groups.bookmarks;",
    "    pinned.forEach(function(m){ var o = document.createElement('option'); o.value = m.id; o.textContent = '★ ' + m.label; g.appendChild(o); });",
    "    sel.appendChild(g);",
    "  }",
    "  list.forEach(function(m) {",
    "    if (!used[m.group]) { used[m.group] = document.createElement('optgroup'); used[m.group].label = groups[m.group] || m.group; sel.appendChild(used[m.group]); }",
    "    var o = document.createElement('option'); o.value = m.id; o.textContent = m.label;",
    "    used[m.group].appendChild(o);",
    "  });",
    "  hydrating = false;",
    "}",
    "function thinkingOptions(modelId, current) {",
    "  var m = catalog.find(function(x){ return x.id === modelId; });",
    "  var opts = (m && m.thinking) ? m.thinking : ['auto'];",
    "  var sel = $('thinking'); if (!sel) return;",
    "  sel.innerHTML = '';",
    "  var list = opts.indexOf('auto') >= 0 ? opts : ['auto'].concat(opts);",
    "  list.forEach(function(tk) { var o = document.createElement('option'); o.value = tk; o.textContent = tk; sel.appendChild(o); });",
    "  sel.value = (current && list.indexOf(current) >= 0) ? current : (opts[0] || 'auto');",
    "  if (!m || !m.thinking || !m.thinking.length) {",
    "    sel.classList.add('no-think');",
    "    sel.title = 'No reasoning adjustment for this model';",
    "  } else {",
    "    sel.classList.remove('no-think');",
    "    sel.title = 'Reasoning Intensity: ' + opts.join(', ');",
    "  }",
    "}",
    "function updateModelBadges(modelId) {",
    "  var bar = $('modelBadgeBar');",
    "  if (!bar) return;",
    "  bar.innerHTML = '';",
    "  var m = catalog.find(function(x){ return x.id === modelId; });",
    "  if (!m) return;",
    "  function fmtNum(n) {",
    "    if (!n) return '';",
    "    if (n >= 1000000) return (n / 1000000).toFixed(n % 1000000 === 0 ? 0 : 1) + 'M';",
    "    if (n >= 1000) return Math.round(n / 1000) + 'K';",
    "    return String(n);",
    "  }",
    "  var ctxLen = m.context || m.context_length;",
    "  if (ctxLen) {",
    "    var bCtx = document.createElement('span');",
    "    bCtx.className = 'chip chip-ctx';",
    "    bCtx.textContent = '⛁ ' + fmtNum(ctxLen) + ' ctx';",
    "    bCtx.title = 'Context window: ' + ctxLen.toLocaleString() + ' tokens';",
    "    bar.appendChild(bCtx);",
    "  }",
    "  var maxOut = m.maxOut || m.max_output;",
    "  if (maxOut) {",
    "    var bOut = document.createElement('span');",
    "    bOut.className = 'chip chip-out';",
    "    bOut.textContent = '⚡ ' + fmtNum(maxOut) + ' out';",
    "    bOut.title = 'Max output: ' + maxOut.toLocaleString() + ' tokens';",
    "    bar.appendChild(bOut);",
    "  }",
    "  if (m.tags && m.tags.length) {",
    "    m.tags.slice(0, 3).forEach(function(tag) {",
    "      var bTag = document.createElement('span');",
    "      var isFree = tag.toLowerCase().indexOf('free') >= 0;",
    "      bTag.className = 'chip ' + (isFree ? 'chip-free' : 'chip-tag');",
    "      bTag.textContent = tag;",
    "      bar.appendChild(bTag);",
    "    });",
    "  }",
    "}",
    "function setBusy(b) {",
    "  busy = b;",
    "  var bsn = $('btnSend');",
    "  var bst = $('btnStop');",
    "  var bw = $('btnWeb');",
    "  var st = $('status');",
    "  var dot = $('statusDot');",
    "  var inp = $('input');",
    "  if (busy) {",
    "    if (bsn) bsn.style.display = 'none';",
    "    if (bst) { bst.style.display = 'inline-flex'; bst.disabled = false; }",
    "    if (bw) bw.disabled = true;",
    "    if (inp) { inp.setAttribute('aria-disabled', 'true'); inp.setAttribute('readonly', ''); }",
    "    if (st) st.textContent = (locale === 'id' ? 'Memproses…' : 'Generating…');",
    "    if (dot) { dot.className = 'status-dot dot-busy'; dot.title = locale === 'id' ? 'Model sedang memproses…' : 'Model is generating…'; }",
    "  } else {",
    "    if (bsn) { bsn.style.display = 'inline-flex'; bsn.disabled = false; }",
    "    if (bst) { bst.style.display = 'none'; }",
    "    if (bw) bw.disabled = false;",
    "    if (inp) { inp.removeAttribute('aria-disabled'); inp.removeAttribute('readonly'); }",
    "    var mdlSel = $('model');",
    "    if (st && mdlSel) st.textContent = (locale === 'id' ? 'Siap' : 'Ready') + ' · ' + mdlSel.value;",
    "    if (dot) { dot.className = 'status-dot dot-ready'; dot.title = locale === 'id' ? 'Siap — klik untuk bertanya' : 'Ready — type to chat'; }",
    "  }",
    "}",
    "function autoResizeInput() {",
    "  var inp = $('input');",
    "  if (!inp) return;",
    "  inp.style.height = 'auto';",
    "  var nextH = Math.min(Math.max(inp.scrollHeight, 64), 200);",
    "  inp.style.height = nextH + 'px';",
    "}",
    "function renderUsage(u) {",
    "  var el = $('usageBox');",
    "  if (!el || !u) return;",
    "  el.textContent = 'Last tokens in ' + (u.prompt_tokens || 0) + ' / out ' + (u.completion_tokens || 0) +",
    "    ' · lifetime in ' + (u.lifetime_prompt || 0) + ' / out ' + (u.lifetime_completion || 0) +",
    "    (u.last_model ? ' · ' + u.last_model : '');",
    "}",
    "",
    "// Global click delegation",
    "document.addEventListener('click', function(e) {",
    "  var target = e.target;",
    "  if (!target) return;",
    "  var qc = target.closest('.quick-card');",
    "  if (qc && qc.dataset.prompt) {",
    "    var inp = $('input');",
    "    if (inp) {",
    "      inp.value = qc.dataset.prompt;",
    "      autoResizeInput();",
    "      inp.focus();",
    "    }",
    "    return;",
    "  }",
    "  if (target.classList && target.classList.contains('code-copy') || target.closest('.code-copy')) {",
    "    var btn = target.closest('.code-copy') || target;",
    "    var box = btn.closest('.code-box');",
    "    if (!box) return;",
    "    var codeEl = box.querySelector('pre code');",
    "    var txt = codeEl ? (codeEl.textContent || '') : '';",
    "    if (navigator.clipboard) {",
    "      navigator.clipboard.writeText(txt).then(function() {",
    "        var prev = btn.dataset.copied ? btn.dataset.orig : btn.innerHTML;",
    "        btn.dataset.copied = '1';",
    "        btn.dataset.orig = prev;",
    "        btn.innerHTML = '✓ ' + (locale === 'id' ? 'Tersalin' : 'Copied');",
    "        setTimeout(function() {",
    "          if (btn.dataset.orig) {",
    "            btn.innerHTML = btn.dataset.orig;",
    "            delete btn.dataset.copied;",
    "            delete btn.dataset.orig;",
    "          }",
    "        }, 1500);",
    "      });",
    "    }",
    "  }",
    "});",
    "",
    "// Wire up buttons",
    "var bSet = $('btnSet'); if (bSet) bSet.onclick = function(){ vscode.postMessage({ type: 'loadSettings' }); show('settings'); };",
    "var bBack = $('btnBack'); if (bBack) bBack.onclick = function(){ show('chat'); };",
    "var bNew = $('btnNew'); if (bNew) bNew.onclick = function(){",
    "  activeStreamEl = null; var msgs = $('msgs'); if (msgs) msgs.innerHTML = '';",
    "  var wc = $('welcomeCard'); if (wc) { if (msgs) msgs.appendChild(wc); wc.style.display = 'flex'; }",
    "  welcomed = true; addMsg('sys', t('taskNew'));",
    "  setBusy(false);",
    "  var inp = $('input'); if (inp) { inp.value = ''; inp.style.height = ''; }",
    "  vscode.postMessage({ type: 'newTask' });",
    "};",
    "var bStop = $('btnStop'); if (bStop) bStop.onclick = function(){",
    "  vscode.postMessage({ type: 'stop' });",
    "  setBusy(false);",
    "};",
    "var bExp = $('btnExport'); if (bExp) bExp.onclick = function(){ vscode.postMessage({ type: 'exportTranscript' }); };",
    "var bSnap = $('btnSnap'); if (bSnap) bSnap.onclick = function(){ vscode.postMessage({ type: 'saveSnapshot' }); };",
    "var bWeb = $('btnWeb'); if (bWeb) bWeb.onclick = function(){",
    "  var inpEl = $('input');",
    "  var q = ((inpEl && inpEl.value) || '').trim();",
    "  if (!q || busy) { if (!q) addMsg('sys', 'Type a query or URL, then press Web.'); return; }",
    "  addMsg('user', q);",
    "  var isUrl = q.startsWith('http://') || q.startsWith('https://');",
    "  addMsg('sys', isUrl ? 'Crawling page via TinyFish…' : 'Searching web via TinyFish…');",
    "  if (inpEl) { inpEl.value = ''; inpEl.style.height = ''; }",
    "  setBusy(true);",
    "  vscode.postMessage({ type: 'webSearch', text: q });",
    "};",
    "var bStar = $('btnStar'); if (bStar) bStar.onclick = function(){",
    "  var mdl = $('model'); var id = mdl ? mdl.value : '';",
    "  vscode.postMessage({ type: 'toggleBookmark', model: id });",
    "};",
    "var thm = $('theme'); if (thm) thm.onchange = function(){",
    "  applyTheme(thm.value);",
    "  vscode.postMessage({ type: 'setTheme', theme: thm.value });",
    "};",
    "function bindFooter(id) {",
    "  var el = $(id); if (!el) return;",
    "  el.onclick = function(){ vscode.postMessage({ type: 'openUrl', url: 'https://alsyundawy.com' }); };",
    "}",
    "bindFooter('footerCredit'); bindFooter('footerCredit2');",
    "function renderFooter(id) {",
    "  var el = $(id); if (!el) return;",
    "  var yr = new Date().getFullYear();",
    '  el.innerHTML = \'<span class="foot-sparkle" aria-hidden="true">✦</span>\' +',
    "    '<span class=\"foot-brand\">ALSYUNDAWY IT SOLUTION</span>' +",
    '    \'<span class="foot-dot" aria-hidden="true">•</span>\' +',
    "    '<span class=\"foot-copy\">COPY LEFT 2023–' + yr + '</span>';",
    "}",
    "renderFooter('footerCredit'); renderFooter('footerCredit2');",
    "",
    "document.querySelectorAll('.modes button').forEach(function(b) {",
    "  b.onclick = function() {",
    "    document.querySelectorAll('.modes button').forEach(function(x){ x.classList.remove('on'); x.setAttribute('aria-selected','false'); });",
    "    b.classList.add('on'); b.setAttribute('aria-selected','true');",
    "    vscode.postMessage({ type: 'setMode', mode: b.dataset.mode });",
    "  };",
    "});",
    "var agSel = $('agent'); if (agSel) agSel.onchange = function(){ var v = agSel.value; if (v) vscode.postMessage({ type: 'setMode', mode: v }); };",
    "var mdlSel = $('model'); if (mdlSel) mdlSel.onchange = function(){",
    "  if (hydrating) return;",
    "  thinkingOptions(mdlSel.value, ($('thinking') || {}).value);",
    "  updateModelBadges(mdlSel.value);",
    "  var bStar2 = $('btnStar'); if (bStar2) bStar2.textContent = (bookmarks || []).indexOf(mdlSel.value) >= 0 ? '★' : '☆';",
    "  vscode.postMessage({ type: 'setModel', model: mdlSel.value });",
    "  vscode.postMessage({ type: 'setThinking', thinking: ($('thinking') || { value: 'auto' }).value });",
    "};",
    "var thkSel = $('thinking'); if (thkSel) thkSel.onchange = function(){ if (!hydrating) vscode.postMessage({ type: 'setThinking', thinking: thkSel.value }); };",
    "var lcSel = $('locale'); if (lcSel) lcSel.onchange = function(){",
    "  locale = lcSel.value === 'id' ? 'id' : 'en'; applyLocale();",
    "  vscode.postMessage({ type: 'setLocale', locale: locale });",
    "};",
    "function bindKeyInput(el) {",
    "  if (!el) return;",
    "  el.addEventListener('focus', function() {",
    "    if (el.dataset.saved === '1') el.select();",
    "  });",
    "  el.addEventListener('input', function() {",
    "    if (el.dataset.saved === '1') el.dataset.saved = '0';",
    "  });",
    "}",
    "bindKeyInput($('apiKey'));",
    "bindKeyInput($('tinyfishApiKey'));",
    "",
    "var bSave = $('btnSave'); if (bSave) bSave.onclick = function(){",
    "  bSave.disabled = true;",
    "  var origLabel = bSave.textContent;",
    "  bSave.textContent = (locale === 'id' ? 'Menyimpan & Mengetes…' : 'Saving & Testing…');",
    "  setTimeout(function(){ bSave.disabled = false; bSave.textContent = t('save'); }, 6000);",
    "  var ak = $('apiKey');",
    "  var akVal = (ak && ak.dataset.saved === '1') ? '' : ((ak && ak.value) || '');",
    "  var tf = $('tinyfishApiKey');",
    "  var tfVal = (tf && tf.dataset.saved === '1') ? '' : ((tf && tf.value) || '');",
    "  vscode.postMessage({",
    "    type: 'saveSettings',",
    "    apiKey: akVal,",
    "    baseUrl: ($('baseUrl') || { value: '' }).value,",
    "    tinyfishApiKey: tfVal,",
    "    model: ($('defModel') || { value: '' }).value,",
    "    thinking: ($('defThink') || { value: 'high' }).value,",
    "    locale: ($('locale') || { value: 'en' }).value,",
    "    theme: ($('theme') || { value: 'auto' }).value",
    "  });",
    "};",
    "var bSend = $('btnSend'); if (bSend) bSend.onclick = send;",
    "var inpEl2 = $('input');",
    "if (inpEl2) {",
    "  inpEl2.addEventListener('input', autoResizeInput);",
    "  inpEl2.addEventListener('keydown', function(e) {",
    "    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); }",
    "  });",
    "}",
    "function send() {",
    "  var inpEl = $('input');",
    "  var text = ((inpEl && inpEl.value) || '').trim();",
    "  if (!text || busy) return;",
    "  setBusy(true);",
    "  if (inpEl) { inpEl.value = ''; inpEl.style.height = ''; }",
    "  addMsg('user', text);",
    "  activeStreamEl = addMsg('assistant', '');",
    "  if (activeStreamEl) activeStreamEl.dataset.stream = '1';",
    "  vscode.postMessage({ type: 'chat', text: text });",
    "}",
    "",
    "window.addEventListener('message', function(e) {",
    "  var m = e.data;",
    "  if (m.type === 'showSettings') { vscode.postMessage({ type: 'loadSettings' }); show('settings'); }",
    "  if (m.type === 'usage') renderUsage(m.usage);",
    "  if (m.type === 'searchResult') { addMsg('sys', m.text); setBusy(false); }",
    "  if (m.type === 'init') {",
    "    hydrating = true;",
    "    catalog = m.catalog;",
    "    bookmarks = m.bookmarks || [];",
    "    applyTheme(m.theme || 'auto');",
    "    var thEl = $('theme'); if (thEl) thEl.value = theme;",
    "    var bStar2 = $('btnStar'); if (bStar2) bStar2.textContent = bookmarks.indexOf(m.model) >= 0 ? '★' : '☆';",
    "    if (m.usage) renderUsage(m.usage);",
    "    var hb = $('homeBox'); if (hb && m.homeDir) hb.textContent = 'Global config: ' + m.homeDir;",
    "    fillModels($('model'), catalog);",
    "    fillModels($('defModel'), catalog);",
    "    var mdSel = $('model'); if (mdSel) mdSel.value = m.model;",
    "    var dmSel = $('defModel'); if (dmSel) dmSel.value = m.model;",
    "    thinkingOptions(m.model, m.thinking);",
    "    updateModelBadges(m.model);",
    "    var dtSel = $('defThink');",
    "    if (dtSel) {",
    "      dtSel.innerHTML = '';",
    "      ['auto','instant','low','medium','high','max','off'].forEach(function(tk) { var o = document.createElement('option'); o.value = tk; o.textContent = tk; dtSel.appendChild(o); });",
    "      dtSel.value = m.thinking;",
    "    }",
    "    var buEl = $('baseUrl'); if (buEl) buEl.value = m.baseUrl;",
    "    var akEl = $('apiKey');",
    "    if (akEl) {",
    "      if (m.hasKey) {",
    "        akEl.value = '••••••••••••••••';",
    "        akEl.dataset.saved = '1';",
    "      } else {",
    "        akEl.value = '';",
    "        akEl.dataset.saved = '0';",
    "      }",
    "    }",
    "    var tfEl = $('tinyfishApiKey');",
    "    if (tfEl) {",
    "      if (m.hasTinyfishKey || (m.tinyfishApiKey && m.tinyfishApiKey.trim())) {",
    "        tfEl.value = '••••••••••••••••';",
    "        tfEl.dataset.saved = '1';",
    "      } else {",
    "        tfEl.value = '';",
    "        tfEl.dataset.saved = '0';",
    "      }",
    "    }",
    "    locale = m.locale === 'id' ? 'id' : 'en';",
    "    var lcEl = $('locale'); if (lcEl) lcEl.value = locale;",
    "    applyLocale();",
    "    var stEl = $('status'); if (stEl) stEl.textContent = (m.hasKey ? 'Token OK' : (locale==='id'?'Belum ada token':'No token')) + ' · ' + m.model;",
    "    var ag = $('agent');",
    "    if (ag) {",
    "      ag.innerHTML = '';",
    "      var extras = m.extras || { skills: [], agents: [] };",
    "      var opt0 = document.createElement('option');",
    "      opt0.value = ''; opt0.textContent = (extras.skills && extras.skills.length) ? ('Skills: ' + extras.skills.length) : 'Built-in agent';",
    "      ag.appendChild(opt0);",
    "      (extras.agents || []).filter(function(a){ return !a.builtin; }).forEach(function(a) {",
    "        var o = document.createElement('option'); o.value = a.id; o.textContent = a.name; ag.appendChild(o);",
    "      });",
    "      if (m.mode && Array.from(ag.options).some(function(o){ return o.value === m.mode; })) ag.value = m.mode;",
    "    }",
    "    document.querySelectorAll('.modes button').forEach(function(b) {",
    "      var on = b.dataset.mode === m.mode;",
    "      b.classList.toggle('on', on);",
    "      b.setAttribute('aria-selected', on ? 'true' : 'false');",
    "    });",
    "    if (!m.booted && !welcomed) { welcomed = true; addMsg('sys', t('welcome')); }",
    "    hydrating = false;",
    "  }",
    "  if (m.type === 'status') { var stEl2 = $('status'); if (stEl2) stEl2.textContent = m.text; }",
    "  if (m.type === 'setStatus') {",
    "    var ssEl = $('setStatus'); if (ssEl) ssEl.textContent = m.text;",
    "    var bsv = $('btnSave'); if (bsv) { bsv.disabled = false; bsv.textContent = t('save'); }",
    "  }",
    "  if (m.type === 'delta') {",
    "    if (!activeStreamEl) { activeStreamEl = addMsg('assistant', ''); if (activeStreamEl) activeStreamEl.dataset.stream = '1'; }",
    "    activeStreamEl.dataset.raw = (activeStreamEl.dataset.raw || '') + m.text;",
    '    activeStreamEl.innerHTML = renderMd(activeStreamEl.dataset.raw) + \'<span class="typing-cursor" aria-hidden="true">▍</span>\';',
    "    var msgs2 = $('msgs');",
    "    if (msgs2) {",
    "      var isNearBottom = msgs2.scrollHeight - msgs2.scrollTop - msgs2.clientHeight < 120;",
    "      if (isNearBottom) msgs2.scrollTop = msgs2.scrollHeight;",
    "    }",
    "  }",
    "  if (m.type === 'done') {",
    "    if (activeStreamEl) {",
    "      activeStreamEl.innerHTML = renderMd(activeStreamEl.dataset.raw || '');",
    "    }",
    "    activeStreamEl = null;",
    "    document.querySelectorAll('[data-stream]').forEach(function(n){ n.removeAttribute('data-stream'); });",
    "    setBusy(false);",
    "  }",
    "  if (m.type === 'error') {",
    "    activeStreamEl = null;",
    "    addMsg('sys', 'Error: ' + m.text);",
    "    setBusy(false);",
    "  }",
    "});",
    "vscode.postMessage({ type: 'ready' });",
  ];
  return scriptLines.join("\n");
}

const CSS = `
:root {
  --bg: var(--vscode-sideBar-background);
  --panel: var(--vscode-editor-background);
  --fg: var(--vscode-foreground);
  --muted: var(--vscode-descriptionForeground);
  --acc: #0181f8;
  --acc2: #3aa0ff;
  --border: var(--vscode-widget-border, #2a2a2a);
  --input: var(--vscode-input-background);
  --btn: var(--vscode-button-background);
  --btnfg: var(--vscode-button-foreground);
  --focus: var(--vscode-focusBorder, #0181f8);
  --code-bg: var(--vscode-textCodeBlock-background, #1e1e1e);
  --code-fg: var(--vscode-textPreformat-foreground, #d4d4d4);
}
* { box-sizing: border-box; }
html, body { height: 100%; margin: 0; font-family: var(--vscode-font-family), "Segoe UI Variable", ui-sans-serif, system-ui; color: var(--fg); background: var(--bg); font-size: 13px; letter-spacing: 0.01em; }
body.theme-dark { --bg: #0e1116; --panel: #161b22; --fg: #e8edf4; --muted: #8b97a8; --border: #2a3340; --input: #12171e; --btn: #0181f8; --btnfg: #fff; --focus: #3aa0ff; --code-bg: #161b22; --code-fg: #d4d4d4; }
body.theme-light { --bg: #f4f6f9; --panel: #ffffff; --fg: #1a2230; --muted: #5c6b7e; --border: #d7dee8; --input: #ffffff; --btn: #0181f8; --btnfg: #fff; --focus: #0181f8; --code-bg: #f0f0f0; --code-fg: #1a2230; }
.app { display: flex; flex-direction: column; height: 100%; }
.top { padding: 10px 12px 8px; border-bottom: 1px solid var(--border); }
.brand { display: flex; align-items: center; justify-content: space-between; gap: 8px; }
.brand-left { display: flex; align-items: center; gap: 8px; min-width: 0; }
.logo-img { width: 22px; height: 22px; flex-shrink: 0; }
.logo { font-weight: 700; letter-spacing: .02em; }
.logo span { color: var(--acc2); }
.brand-actions { display: flex; gap: 3px; align-items: center; }
.row { display: flex; gap: 6px; margin-top: 8px; flex-wrap: wrap; }
select, input, textarea { background: var(--input); color: var(--fg); border: 1px solid var(--border); border-radius: 8px; padding: 6px 8px; font: inherit; }
select:focus, input:focus, textarea:focus, button:focus-visible { outline: 2px solid var(--focus); outline-offset: 1px; }
select { flex: 1; min-width: 0; }
#thinking { max-width: 92px; }
#thinking.no-think { opacity: 0.65; }
.modes { display: grid; grid-template-columns: repeat(6, 1fr); gap: 3px; margin-top: 8px; }
@media (max-width: 260px) { .modes { grid-template-columns: repeat(3, 1fr); } }
.modes button { border: 1px solid var(--border); background: color-mix(in srgb, var(--panel) 80%, transparent); color: var(--fg); border-radius: 6px; padding: 4px 2px; font-size: 11px; font-weight: 500; cursor: pointer; text-align: center; transition: all .15s ease; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.modes button:hover { border-color: var(--acc); color: var(--acc2); }
.modes button.on { background: var(--btn); color: var(--btnfg); border-color: transparent; font-weight: 600; }
.iconbtn, .primary, .ghost { border: 1px solid var(--border); background: color-mix(in srgb, var(--panel) 80%, transparent); color: var(--fg); border-radius: 8px; padding: 6px 10px; cursor: pointer; transition: background .15s ease, border-color .15s ease, transform .12s ease; font-size: 12px; display: inline-flex; align-items: center; justify-content: center; gap: 4px; }
.modes button:hover, .iconbtn:hover, .ghost:hover { border-color: var(--acc); }
.primary { background: var(--btn); color: var(--btnfg); border-color: transparent; font-weight: 600; }
.primary:active, .ghost:active, .iconbtn:active { transform: translateY(1px); }
.iconbtn { padding: 5px 8px; min-width: 30px; font-size: 12px; }
.iconbtn svg { display: block; flex-shrink: 0; }
.model-badge-bar { display: flex; gap: 4px; margin-top: 6px; flex-wrap: wrap; align-items: center; min-height: 18px; }
.chip { font-size: 10px; font-weight: 600; padding: 2px 6px; border-radius: 4px; border: 1px solid var(--border); line-height: 1.2; letter-spacing: 0.02em; user-select: none; display: inline-flex; align-items: center; gap: 3px; }
.chip-ctx { background: color-mix(in srgb, var(--acc) 14%, transparent); color: var(--acc2); border-color: color-mix(in srgb, var(--acc) 32%, transparent); }
.chip-out { background: color-mix(in srgb, #10b981 14%, transparent); color: #34d399; border-color: color-mix(in srgb, #10b981 32%, transparent); }
.chip-tag { background: color-mix(in srgb, var(--panel) 90%, transparent); color: var(--fg); opacity: 0.9; }
.chip-free { background: color-mix(in srgb, #f59e0b 15%, transparent); color: #fbbf24; border-color: color-mix(in srgb, #f59e0b 35%, transparent); }
.msgs { flex: 1; overflow: auto; padding: 12px; display: flex; flex-direction: column; gap: 10px; }
.msg-wrap { position: relative; }
.msg { border: 1px solid var(--border); border-radius: 12px; padding: 10px 12px; background: var(--panel); word-break: break-word; line-height: 1.5; }
.msg.user { background: color-mix(in srgb, var(--acc) 9%, var(--panel)); border-color: color-mix(in srgb, var(--acc) 38%, var(--border)); }
.msg.user .role { color: var(--acc); }
.msg.assistant { border-color: var(--border); }
.msg.assistant .role { color: var(--acc2); }
.msg.sys { color: var(--muted); font-size: 12px; }
.role { font-size: 10px; text-transform: uppercase; letter-spacing: .08em; margin-bottom: 4px; font-weight: 700; display: flex; justify-content: space-between; align-items: center; }
.role-badge { display: inline-flex; align-items: center; gap: 4px; font-weight: 700; }
.copy-btn { font-size: 10px; cursor: pointer; background: none; border: none; color: var(--muted); padding: 1px 4px; border-radius: 4px; transition: color .15s; letter-spacing: 0; text-transform: none; display: inline-flex; align-items: center; gap: 3px; }
.copy-btn:hover { color: var(--acc2); }
.md h1, .md h2, .md h3, .md h4 { margin: .5em 0 .25em; font-weight: 700; }
.md h1 { font-size: 1.2em; } .md h2 { font-size: 1.1em; } .md h3 { font-size: 1em; }
.md p { margin: .3em 0; }
.md ul, .md ol { margin: .3em 0; padding-left: 1.4em; }
.md li { margin: .15em 0; }
.md code { background: var(--code-bg); color: var(--code-fg); padding: 1px 5px; border-radius: 4px; font-family: var(--vscode-editor-font-family), monospace; font-size: .9em; }
.code-box { border: 1px solid var(--border); border-radius: 8px; margin: 0.6em 0; overflow: hidden; background: var(--code-bg); }
.code-head { display: flex; justify-content: space-between; align-items: center; padding: 4px 10px; background: color-mix(in srgb, var(--panel) 75%, var(--bg)); border-bottom: 1px solid var(--border); font-size: 11px; }
.code-lang { font-family: var(--vscode-editor-font-family), monospace; font-size: 10.5px; color: var(--muted); text-transform: lowercase; font-weight: 600; }
.code-copy { background: none; border: 1px solid transparent; color: var(--muted); font-size: 10px; cursor: pointer; padding: 2px 6px; border-radius: 4px; transition: all 0.15s ease; display: inline-flex; align-items: center; gap: 3px; }
.code-copy:hover { color: var(--fg); background: color-mix(in srgb, var(--panel) 80%, transparent); border-color: var(--border); }
.code-box pre { margin: 0 !important; border: none !important; border-radius: 0 !important; padding: 8px 10px !important; }
.md pre { background: var(--code-bg); border: 1px solid var(--border); border-radius: 8px; padding: 10px 12px; overflow-x: auto; margin: .5em 0; }
.md pre code { background: none; padding: 0; border-radius: 0; display: block; color: var(--code-fg); font-size: .9em; white-space: pre; }
.md blockquote { border-left: 3px solid var(--acc); margin: .3em 0; padding: .2em .8em; color: var(--muted); }
.md strong { font-weight: 700; }
.md em { font-style: italic; }
.md a { color: var(--acc2); text-decoration: none; } .md a:hover { text-decoration: underline; }
.md hr { border: none; border-top: 1px solid var(--border); margin: .6em 0; }
.md table { border-collapse: collapse; width: 100%; margin: .4em 0; font-size: .9em; }
.md th, .md td { border: 1px solid var(--border); padding: 4px 8px; text-align: left; }
.md th { background: var(--code-bg); font-weight: 700; }
.typing-cursor { display: inline-block; color: var(--acc2); animation: blinkCursor 0.8s infinite; font-weight: 700; margin-left: 2px; }
@keyframes blinkCursor { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }

/* Welcome Card & Quick Starts */
.welcome-card { display: flex; flex-direction: column; align-items: center; text-align: center; padding: 18px 8px 12px; margin: auto 0; gap: 6px; }
.welcome-badge { font-size: 9.5px; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; padding: 3px 8px; border-radius: 12px; background: color-mix(in srgb, var(--acc) 16%, transparent); color: var(--acc2); border: 1px solid color-mix(in srgb, var(--acc) 30%, transparent); }
.welcome-title { font-size: 14px; font-weight: 700; color: var(--fg); margin-top: 2px; }
.welcome-desc { font-size: 11.5px; color: var(--muted); max-width: 280px; line-height: 1.4; }
.quick-prompts { display: grid; grid-template-columns: 1fr; gap: 6px; width: 100%; max-width: 320px; margin-top: 8px; }
@media (min-width: 270px) { .quick-prompts { grid-template-columns: 1fr 1fr; } }
.quick-card { display: flex; align-items: center; gap: 6px; padding: 7px 9px; background: color-mix(in srgb, var(--panel) 85%, transparent); border: 1px solid var(--border); border-radius: 8px; text-align: left; cursor: pointer; color: var(--fg); font-size: 11px; transition: all 0.18s ease; }
.quick-card:hover { border-color: var(--acc); background: color-mix(in srgb, var(--acc) 10%, var(--panel)); transform: translateY(-1px); }
.quick-icon { font-size: 12px; flex-shrink: 0; }
.quick-text { font-weight: 500; line-height: 1.25; }

.composer { border-top: 1px solid var(--border); padding: 10px; }
textarea { width: 100%; min-height: 64px; resize: vertical; }
.bar { display: flex; justify-content: space-between; align-items: center; margin-top: 8px; gap: 8px; }
.status-wrap { display: flex; align-items: center; gap: 6px; flex: 1; min-width: 0; overflow: hidden; }
.status-dot { width: 7px; height: 7px; border-radius: 50%; flex-shrink: 0; transition: background 0.2s ease; }
.dot-ready { background: #10b981; box-shadow: 0 0 6px rgba(16, 185, 129, 0.5); }
.dot-busy { background: #f59e0b; box-shadow: 0 0 6px rgba(245, 158, 11, 0.6); animation: dotPulse 1.2s infinite ease-in-out; }
@keyframes dotPulse { 0%, 100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.5; transform: scale(0.85); } }
.bar-actions { display: flex; gap: 6px; align-items: center; }
#btnStop { display: none; background: color-mix(in srgb, #ef4444 18%, transparent); border-color: #ef4444; color: #fca5a5; font-weight: 600; }
#btnStop:hover { background: #ef4444; color: #fff; }
.status { color: var(--muted); font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.screen { display: none; flex-direction: column; height: 100%; }
.screen.on { display: flex; }
.form { padding: 12px; display: flex; flex-direction: column; gap: 10px; overflow: auto; }
.setting-group { background: color-mix(in srgb, var(--panel) 60%, var(--bg)); border: 1px solid var(--border); border-radius: 10px; padding: 10px 12px; display: flex; flex-direction: column; gap: 6px; }
.setting-group-title { font-size: 11px; font-weight: 700; color: var(--fg); text-transform: uppercase; letter-spacing: 0.06em; opacity: 0.85; margin-bottom: 2px; border-bottom: 1px solid color-mix(in srgb, var(--border) 50%, transparent); padding-bottom: 4px; }
label { font-size: 11px; color: var(--muted); }
.hint { color: var(--muted); font-size: 12px; line-height: 1.4; }
.token { letter-spacing: .04em; }
.sr { position:absolute; width:1px; height:1px; overflow:hidden; clip:rect(0 0 0 0); }
.foot-wrap { margin-top: auto; padding: 10px 12px 14px; background: transparent; border: none; display: flex; justify-content: center; align-items: center; width: 100%; box-sizing: border-box; }
.foot, .foot-credit { all: unset; -webkit-appearance: none; appearance: none; background: transparent !important; border: none !important; outline: none !important; box-shadow: none !important; border-radius: 0 !important; padding: 4px 8px !important; margin: 0 !important; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; flex-wrap: wrap; gap: 6px; text-align: center; transition: transform 0.25s cubic-bezier(0.4, 0, 0.2, 1), filter 0.25s ease; user-select: none; width: auto; }
.foot:hover, .foot-credit:hover { transform: translateY(-1px); }
.foot-sparkle { font-size: 11px; line-height: 1; background: linear-gradient(135deg, #f59e0b, #ec4899, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; filter: drop-shadow(0 0 6px rgba(236, 72, 153, 0.6)); animation: footPulse 2.5s ease-in-out infinite; }
.foot-brand { font-size: 10px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; background: linear-gradient(90deg, #06b6d4, #3b82f6, #8b5cf6, #ec4899, #f59e0b, #10b981); background-size: 300% 100%; -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; animation: footRainbow 6s linear infinite; display: inline-block; }
.foot:hover .foot-brand, .foot-credit:hover .foot-brand { filter: drop-shadow(0 0 8px rgba(59, 130, 246, 0.7)); }
.foot-dot { font-size: 8px; color: #ec4899; opacity: 0.8; vertical-align: middle; }
.foot-copy { font-size: 9.5px; font-weight: 500; letter-spacing: 0.06em; background: linear-gradient(90deg, #a78bfa, #38bdf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; opacity: 0.9; }
.foot:hover .foot-copy, .foot-credit:hover .foot-copy { opacity: 1; }
@keyframes footRainbow { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
@keyframes footPulse { 0%, 100% { transform: scale(1); filter: drop-shadow(0 0 4px rgba(245, 158, 11, 0.5)); } 50% { transform: scale(1.25); filter: drop-shadow(0 0 10px rgba(236, 72, 153, 0.9)); } }
.star { min-width: 32px; }
`;

export function getWebviewHtml(
  nonce: string,
  csp: string,
  logoUri: string,
): string {
  const script = getWebviewScript(nonce);
  return [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="UTF-8"/>',
    `<meta http-equiv="Content-Security-Policy" content="${csp}"/>`,
    '<meta name="viewport" content="width=device-width,initial-scale=1"/>',
    "<title>Bailu Agent</title>",
    `<style>${CSS}</style>`,
    "</head>",
    "<body>",
    '<div id="chat" class="app screen on" role="region" aria-label="Bailu Agent Chat">',
    '  <div class="top">',
    '    <div class="brand">',
    '      <div class="brand-left">',
    `        <img class="logo-img" src="${logoUri}" alt="BAILU AI"/>`,
    '        <div class="logo">Bailu <span>Agent</span></div>',
    "      </div>",
    '      <div class="brand-actions">',
    '        <button type="button" class="iconbtn" id="btnExport" title="Export transcript" aria-label="Export transcript">',
    '          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>',
    "        </button>",
    '        <button type="button" class="iconbtn" id="btnSnap" title="Save snapshot" aria-label="Save snapshot">',
    '          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>',
    "        </button>",
    '        <button type="button" class="iconbtn" id="btnNew" title="New task" aria-label="New task">',
    '          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>',
    "        </button>",
    '        <button type="button" class="iconbtn" id="btnSet" title="Settings" aria-label="Settings">',
    '          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>',
    "        </button>",
    "      </div>",
    "    </div>",
    '    <div class="modes" role="tablist" aria-label="Agent">',
    '      <button type="button" data-mode="code" class="on" role="tab" aria-selected="true">Code</button>',
    '      <button type="button" data-mode="plan" role="tab" aria-selected="false">Plan</button>',
    '      <button type="button" data-mode="ask" role="tab" aria-selected="false">Ask</button>',
    '      <button type="button" data-mode="debug" role="tab" aria-selected="false">Debug</button>',
    '      <button type="button" data-mode="review" role="tab" aria-selected="false">Review</button>',
    '      <button type="button" data-mode="arch" role="tab" aria-selected="false">Arch</button>',
    "    </div>",
    '    <div class="row">',
    '      <label class="sr" for="agent">Custom agent</label>',
    '      <select id="agent" aria-label="Custom agent"></select>',
    "    </div>",
    '    <div class="row">',
    '      <label class="sr" for="model">Model</label>',
    '      <select id="model" aria-label="Model"></select>',
    '      <button type="button" class="iconbtn star" id="btnStar" title="Bookmark model" aria-label="Bookmark model">☆</button>',
    '      <label class="sr" for="thinking">Thinking</label>',
    '      <select id="thinking" title="Thinking" aria-label="Thinking"></select>',
    "    </div>",
    '    <div class="model-badge-bar" id="modelBadgeBar" role="note" aria-label="Model specifications"></div>',
    "  </div>",
    '  <div class="msgs" id="msgs" role="log" aria-live="polite">',
    '    <div class="welcome-card" id="welcomeCard">',
    '      <div class="welcome-badge">BAILU AI AGENT</div>',
    '      <div class="welcome-title" id="welcomeTitle">What would you like to build?</div>',
    '      <div class="welcome-desc" id="welcomeDesc">Agentic coding assistant powered by BAILU AI &amp; Antigravity engineering methodology.</div>',
    '      <div class="quick-prompts">',
    '        <button type="button" class="quick-card" data-prompt="Explain the active file, its key components, and architecture pattern.">',
    '          <span class="quick-icon">💡</span>',
    '          <span class="quick-text" id="qExplainText">Explain active file</span>',
    "        </button>",
    '        <button type="button" class="quick-card" data-prompt="Refactor this code for cleaner architecture, security, and performance.">',
    '          <span class="quick-icon">✨</span>',
    '          <span class="quick-text" id="qRefactorText">Refactor &amp; clean</span>',
    "        </button>",
    '        <button type="button" class="quick-card" data-prompt="Generate comprehensive unit tests for this file following TDD.">',
    '          <span class="quick-icon">🧪</span>',
    '          <span class="quick-text" id="qTestsText">Generate unit tests</span>',
    "        </button>",
    '        <button type="button" class="quick-card" data-prompt="Investigate and systematically debug any potential defects or edge cases.">',
    '          <span class="quick-icon">🔍</span>',
    '          <span class="quick-text" id="qDebugText">Debug &amp; find bugs</span>',
    "        </button>",
    "      </div>",
    "    </div>",
    "  </div>",
    '  <div class="composer">',
    '    <label class="sr" for="input">Message</label>',
    '    <textarea id="input" placeholder="Task\u2026 (Enter send, Shift+Enter newline)"></textarea>',
    '    <div class="bar">',
    '      <div class="status-wrap">',
    '        <span class="status-dot dot-ready" id="statusDot" aria-hidden="true"></span>',
    '        <span class="status" id="status" role="status">Ready</span>',
    "      </div>",
    '      <div class="bar-actions">',
    '        <button type="button" class="ghost" id="btnWeb" title="Web search &amp; crawler" aria-label="Web search">',
    '          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg> <span>Web</span>',
    "        </button>",
    '        <button type="button" class="ghost" id="btnStop" title="Stop" aria-label="Stop generation"><span>■ Stop</span></button>',
    '        <button type="button" class="primary" id="btnSend" title="Send (Enter)" aria-label="Send message">',
    '          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg> <span>Send</span>',
    "        </button>",
    "      </div>",
    "    </div>",
    "  </div>",
    '  <div class="foot-wrap">',
    '    <button type="button" class="foot-credit" id="footerCredit" title="https://alsyundawy.com" aria-label="Developer website">',
    '      <span class="foot-sparkle" aria-hidden="true">✦</span>',
    '      <span class="foot-brand">ALSYUNDAWY IT SOLUTION</span>',
    '      <span class="foot-dot" aria-hidden="true">•</span>',
    '      <span class="foot-copy">COPY LEFT 2023–2026</span>',
    "    </button>",
    "  </div>",
    "</div>",
    '<div id="settings" class="app screen" role="region" aria-label="Settings">',
    '  <div class="top">',
    '    <div class="brand">',
    '      <div class="brand-left">',
    `        <img class="logo-img" src="${logoUri}" alt=""/>`,
    '        <div class="logo" id="lblSettingsTitle">Settings</div>',
    "      </div>",
    '      <button type="button" class="iconbtn" id="btnBack" aria-label="Back">',
    '        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>',
    "      </button>",
    "    </div>",
    "  </div>",
    '  <div class="form">',
    '    <div class="setting-group">',
    '      <div class="setting-group-title">Authentication &amp; Keys</div>',
    '      <div class="hint" id="hintSecret">The token is stored in VS Code SecretStorage, not in settings.json.</div>',
    '      <label for="apiKey" id="lblToken">API Token</label>',
    '      <input class="token" id="apiKey" type="password" autocomplete="off" placeholder="sk-\u2026 or Bailu token"/>',
    '      <label for="baseUrl">Base URL</label>',
    '      <input id="baseUrl" placeholder="https://bailucode.com/openapi/v1"/>',
    '      <label for="tinyfishApiKey" id="lblTinyfish">TinyFish API Key (Search &amp; Crawler)</label>',
    '      <input class="token" id="tinyfishApiKey" type="password" autocomplete="off" placeholder="sk-tinyfish-\u2026"/>',
    "    </div>",
    '    <div class="setting-group">',
    '      <div class="setting-group-title">Model &amp; Reasoning Defaults</div>',
    '      <label for="defModel" id="lblDefModel">Default model</label>',
    '      <select id="defModel"></select>',
    '      <label for="defThink" id="lblDefThink">Default thinking</label>',
    '      <select id="defThink"></select>',
    "    </div>",
    '    <div class="setting-group">',
    '      <div class="setting-group-title">Preferences</div>',
    '      <label for="locale" id="lblLocale">Language</label>',
    '      <select id="locale" aria-label="Language">',
    '        <option value="en">English</option>',
    '        <option value="id">Bahasa Indonesia</option>',
    "      </select>",
    '      <label for="theme" id="lblTheme">Theme</label>',
    '      <select id="theme" aria-label="Theme">',
    '        <option value="auto">Auto</option>',
    '        <option value="dark">Dark</option>',
    '        <option value="light">Light</option>',
    "      </select>",
    "    </div>",
    '    <div class="setting-group">',
    '      <div class="setting-group-title">Telemetry &amp; Usage</div>',
    '      <div class="status" id="setStatus" role="status"></div>',
    '      <div class="hint" id="usageBox">Tokens: \u2014</div>',
    '      <div class="hint" id="homeBox">Global config: \u2014</div>',
    "    </div>",
    '    <button type="button" class="primary" id="btnSave" aria-label="Save settings and test connection">Save &amp; test connection</button>',
    '    <div class="foot-wrap">',
    '      <button type="button" class="foot-credit" id="footerCredit2" title="https://alsyundawy.com" aria-label="Developer website">',
    '        <span class="foot-sparkle" aria-hidden="true">✦</span>',
    '        <span class="foot-brand">ALSYUNDAWY IT SOLUTION</span>',
    '        <span class="foot-dot" aria-hidden="true">•</span>',
    '        <span class="foot-copy">COPY LEFT 2023–2026</span>',
    "      </button>",
    "    </div>",
    "  </div>",
    "</div>",
    `<script nonce="${nonce}">`,
    script,
    "</script>",
    "</body>",
    "</html>",
  ].join("\n");
}
